FROM python:3.8-alpine

ADD requirements.txt /requirements.txt

RUN pip3 install --no-cache-dir -r /requirements.txt

ADD minion.py /minion.py

# tell the port number the container should expose
EXPOSE 8888

CMD ["python3", "/minion.py"]